services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL_asyncpg: postgresql+asyncpg://myuser:mypassword@postgres/mydatabase
      REDIS_URL: redis://redis:6379
      JWT_PRIVATE_KEY: /keys/jwt-private.pem
      JWT_PUBLIC_KEY: /keys/jwt-public.pem
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/src/certs:/keys
    ports:
      - "8000:8000"
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["sh", "-c", "npm install && npm run dev -- --host"]

volumes:
  pgdata:
  jwt_keys:
  redis_data:
