# Используем официальную Python-образ
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код
COPY . /app/

# Открываем порты
EXPOSE 8000

# Команда для применения миграций и запуска приложения
CMD ["sh", "-c", "alembic upgrade head && python src/main.py --host 0.0.0.0 --port 8000"]
