"""empty message

Revision ID: 17553b395afc
Revises: 3beecfcad14d
Create Date: 2025-03-11 15:45:05.277526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17553b395afc'
down_revision: Union[str, None] = '3beecfcad14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'authorized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
