"""empty message

Revision ID: 36464f08c81d
Revises: 7cb35a1ffcbe
Create Date: 2025-02-23 19:13:45.928729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36464f08c81d'
down_revision: Union[str, None] = '7cb35a1ffcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized', sa.Boolean(), nullable=False))
    op.drop_column('users', 'Authorized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Authorized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'authorized')
    # ### end Alembic commands ###
