"""empty message

Revision ID: b941dd7aa4dd
Revises: 5df3d0bb7ca8
Create Date: 2025-02-25 21:47:56.931826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b941dd7aa4dd'
down_revision: Union[str, None] = '5df3d0bb7ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
